language: ruby
rvm:
- 2.2
before_script:
- gem install awesome_bot
script:
- awesome_bot README.md --allow-redirect --allow-dupe --allow-ssl
notifications:
  email: false
  slack:
    secure: Mq0Ng3mQGTyytd6s3srUIuarE+lOWzigRXvge/4p15v9vicGv1juDjaab1iJBEgmiD2+AI/EZFlJJ79fvRz1KDTvmk+YJNXrQTUgCunAmo0TvR3vGGwcFkUU2+iYDcqJHTtxmiS3PwrKynVafM02ifxrqVCc0QNC1AbyPFJ8De9aqNgjLc80PVqmkoDaKt7tmi6ZIrsfKghhxvcJmhvwHp3A93hJlkl9P4/OQn4Tj1/xa/eBxTYPcdLx/DPR5peuOplzkM0QnjQMV3JS+qFyhbfxqKAvtXlIZF0fsuPuF4aHmKQKDaHLeM8MVjJtE5jT3T0LnRCSK1Esz+ki2ewTvXbmS+WzD9CJY16qwoZ9xUYJN15jkyhYdlYm6GlKsRpf6RDclxSfFjPvrDXDnQJRTW+clTD3PxbFrp2iCkQDMxhQ1n5uR0ZKHfyAgbRdzsQRtCXXUqKI1NP59JR3ed7oSrzRttLSBIgDo52gDYuBsaF7tHi9pTNP5Ddn+FrRIPFRQO/QRN5lGm2SIlYozzbnXX8S8mv2UBE3WiO8TLY84ynNRY64b/GeH+O0iyvHo90XEHMfc0KRvwkWFpQOVaz27yAXygvqEf7Kxwl249HaK8aH8hqRh8VTw+4mt6pR56Ezt25tcFyG+aNMSlo9A7TKDkc7RF8+JIW2kPqfO7t5KBo=
